### ISSUE TITLE
Ending up in white pages

### ISSUE THREAD

**Issue by pumatertion** [NamelessCoder/TYPO3.Fluid#10]
After https://github.com/NamelessCoder/TYPO3.Fluid/issues/9 i am ending not in exceptions but in a white page. First run without generated caches gives me a result i expected. After this first run the templates are compiled and i am ending up in a white page with null content.

I am totaly unsure about the namespace. ```<fluid>``` not ```<f:fluid>``` right?
Is it enough to define a namespace in a layout or do i need to define it everywhere something different from ```<f:..>``` happens?

**Comment by NamelessCoder** [comment]
This one is fixed now - but another issue has been spotted in how sibling nodes are processed. Seems if a ViewHelperNode has non-ViewHelperNode siblings (i.e. TextNode) the resulting rendering when compiled is missing the contents of the non-ViewHelperNode siblings... just wanted to let you know in case you're also affected by that one.

**Comment by pumatertion** [comment]
Thank you!
