### ISSUE TITLE
Namespaces and inline ViewHelper seems not to work

### ISSUE THREAD

**Issue by pumatertion** [NamelessCoder/TYPO3.Fluid#11]
Does not work as expexted:
```
<fluid xmlns:abc="Foo\Bar\ViewHelpers">
	// This will be totaly ignored. Also no <div> is printed out.
	<div>SystemLocale: {abc:foo.bar()}</div>
</fluid>
```

Works as expected:
```
<fluid xmlns:abc="Foo\Bar\ViewHelpers">
	// Wrap it in an alias view helper anything works fine.
	<f:alias map="{systemLocale:'{abc:foo.bar()}'}">
		<div>SystemLocale: {systemLocale}</div>
	<f:alias>
</fluid>
```

**Comment by NamelessCoder** [comment]
Hmm - I'm afraid I'm unable to reproduce that one locally. There's an example file that uses this syntax:

```
<fluid xmlns:my="http://typo3.org/ns/TYPO3/FluidExample/ViewHelpers">
<f:layout name="Default" />

<f:section name="Main">
NamespaceResolving template from Singles.

<!-- Use of custom-namespace ViewHelper: -->
<my:custom page="123" />

<!-- Use of custom-namespace ViewHelper, inline mode: -->
{my:custom(page: 321)}

</f:section>
</fluid>
```

Which I added to test this very case. Strange....

**Comment by NamelessCoder** [comment]
Is this possibly related to your Q last night about IDE cleaning up "unused namespaces" which aren't unused but are not detected because only the inline syntax is used? If your IDE removed the namespace import and you didn't notice, then that might explain the problem...

**Comment by pumatertion** [comment]
could you try without using <my.custom> in the same template? only the inline one?
´´´
<fluid xmlns:my="http://typo3.org/ns/TYPO3/FluidExample/ViewHelpers">
<f:layout name="Default" />

<f:section name="Main">
NamespaceResolving template from Singles.


{my:custom(page: 321)}

</f:section>
</fluid>

**Comment by NamelessCoder** [comment]
I may have located a bug in the compiling of the nodes involved with this - does it make any difference if you disable the cache? Just to know if the problem I've located has anything to do with this one...

**Comment by NamelessCoder** [comment]
Long time since this was relevant :)
