### ISSUE TITLE
Incorrect license

### ISSUE THREAD

**Issue by robertlemke** [NamelessCoder/TYPO3.Fluid#12]
Hi Claus,

I appreciate that you chose to use the MIT license for the standalone Fluid project, but since it is based on TYPO3 Fluid, which is currently licensed under the LGPL, you will need to continue licensing it under LGPL until the license for Fluid has been changed to MIT by the TYPO3 Association.

If you have any questions regarding the progress of the license change, please get in touch with Olivier Dobberkau.

Cheers,
Robert

**Comment by NamelessCoder** [comment]
Hi Robert,

You're right of course. Since this will be living in public for a while I'll put the LGPL license file back and await the official switch.

Cheers,
Claus

**Comment by robertlemke** [comment]
Thanks! And let's hope for the best ;-)

**Comment by NamelessCoder** [comment]
I'm optimistic, I think people will agree MIT is a good choice and won't object to the change. Fingers crossed ;)
