### ISSUE TITLE
Issue with rendering sections from cache

### ISSUE THREAD

**Issue by radmiraal** [NamelessCoder/TYPO3.Fluid#13]
The following doesn't work when using the SimpleFileCache (only the first rendering works, cached breaks):

```xml
	<f:render section="foo" />
	<f:section name="foo">
		foo
	</f:section>
```

This leads to `Fatal error: Uncaught exception 'TYPO3\Fluid\View\Exception\InvalidSectionException' with message 'Section "foo" does not exist.'`

**Comment by NamelessCoder** [comment]
Hi @radmiraal - could you clarify if you put that template code in a Layout, a Template or a Partial? This will have an effect on how/where the expected section is called and the info will help in tracking down the problem!

Thanks in advance :)

**Comment by radmiraal** [comment]
oof, will create some snippets... but from the top of my head this was done in a layout.

**Comment by NamelessCoder** [comment]
With some shame I must admit I am not 100% sure about the following, but I think the "Fluid RFC" (if there ever was such a thing) actually says that sections cannot be defined in the Layout itself and that this is the only place sections cannot be defined. The reason being that when a Layout is rendered it is always through a Template and any `f:render` calls that are placed in the Layout will always expect the section to exist in the Template - without ever checking if it exists in the Layout.

I am also not completely sure if this *should* be done; checking if section is defined in the Layout. It is technically possible to do, but might cause some confusion, e.g. which has priority if section is defined in both the Layout and Template...

**Comment by NamelessCoder** [comment]
Hi Rens,

Any news about this one? Is it an issue with the cached template/layout PHP file or caused by trying to define a section in the Layout itself?

**Comment by radmiraal** [comment]
Hey, didn't find time to look into it yet. Maybe I find some time during the current sprint...

**Comment by NamelessCoder** [comment]
Thanks Rens - if you don't mind, please (re-)report the issue if it is still relevant, at the "real" Fluid repository that's now live ;)

At some point I will shut down this package or shell it out to just be a collection of aliases for `TYPO3Fluid\Fluid`.

https://github.com/TYPO3Fluid/Fluid

**Comment by radmiraal** [comment]
aah, cool ;)  No prob, will re-open if I find the time... If not consider it a non-issue ;)
