### ISSUE TITLE
Passing arguments to sections is broken

### ISSUE THREAD

**Issue by radmiraal** [NamelessCoder/TYPO3.Fluid#14]
Currently 
```xml
	{menuItems -> f:debug()}
	<f:render section="menu" arguments="{items: menuItems}" />

	<f:section name="menu">
		{items -> f:debug()}
	</f:section>

```

Leads to a successful dump of menuItems, but the dump inside the section dumps NULL.

**Comment by NamelessCoder** [comment]
Thanks for the report! I'm not sure why this would be happening... There's an example included which uses passing of arguments this way: https://github.com/NamelessCoder/TYPO3.Fluid/blob/development/examples/Resources/Private/Templates/Default/Default.html#L8 and the example appears to render correctly (note: `development` branch which is still not merged - I'm working on an issue in condition nodes once they are compiled, which currently have a few hiccups when the expressions are complex).

Do you define *and* render the section in the same template - and is it, as I assume, a Template resource?

**Comment by radmiraal** [comment]
I retested it with the following code:

```php
<?php

use NamelessCoder\Fluid\View\TemplatePaths;
use NamelessCoder\Fluid\View\TemplateView;

require('../Packages/Libraries/autoload.php');

$paths = new TemplatePaths();
$paths->setTemplateRootPaths([__DIR__]);
$paths->setLayoutRootPaths([__DIR__ . '/Layouts/']);
$paths->setPartialRootPaths([__DIR__ . '/Partials/']);

$view = new TemplateView($paths);
$view->getTemplatePaths()->setTemplatePathAndFilename(__DIR__ . '/test.html');
$view->assign(
	'menuItems',
	[
		[
			'label' => 'item 1',
			'children' => [
				[
					'label' => 'item 1 - child 1'
				],
				[
					'label' => 'item 1 - child 2'
				]
			]
		],
		[
			'label' => 'item 2',
			'children' => [
				[
					'label' => 'item 2 - child 1'
				],
				[
					'label' => 'item 2 - child 2'
				]
			]
		]
	]
);
echo $view->render('index');
```

```xml
<f:render section="menu" arguments="{items: menuItems}" />

<f:section name="menu">
	<ul>
		<f:for each="{items}" as="item">
			<li>
				{item.label}
				<f:if condition="{item.children}">
					<f:render section="menu" arguments="{items: item.children}" />
				</f:if>
			</li>
		</f:for>
	</ul>
</f:section>
```

and now it just works... Guess I wasn't on dev-master when I tested before then. So, seems to work :-)

**Comment by NamelessCoder** [comment]
Thanks for the follow-up! I hope to merge development to master later today, including a fix for those complex BooleanNode expressions.

**Comment by radmiraal** [comment]
yw ;-) must say hacking around in plain 'non-frameworky' php with fluid is quite awesome, so thanks a lot for your effort ;)

**Comment by NamelessCoder** [comment]
![bow](https://cloud.githubusercontent.com/assets/2228052/8281423/295e1f62-18e8-11e5-904b-52c602b9cb63.jpg)
