### ISSUE TITLE
Example for automatic template resolution

### ISSUE THREAD

**Issue by 7elix** [NamelessCoder/TYPO3.Fluid#2]
Bring example where template path is resolved automatically by Controller name and Action

**Comment by NamelessCoder** [comment]
I bet https://github.com/NamelessCoder/TYPO3.Fluid/blob/master/examples/example_mvc.php can be improved, along with the related template! It's not super obvious how a different action would be rendered... perhaps the `$output` can be generated with two different calls to `render()` with different actions to better illustrate?

**Comment by NamelessCoder** [comment]
Did a little elaboration: https://github.com/NamelessCoder/TYPO3.Fluid/commit/a106ec1151c4fd90c6160242a7ef14f0e0c3276a

At least now it involves a second controller and other action name; an *actual* MVC example that has a proper controller would have to come in the shape of another package imho ;)
