### ISSUE TITLE
Template/Partial/Layout folder names

### ISSUE THREAD

**Issue by 7elix** [NamelessCoder/TYPO3.Fluid#5]
Might consider changing the TemplateA and TemplateB folder names to Template and TemplateOverride – or similar, more verbose. Might make the first steps easier at a stage when the setTemplateRootPaths include files are not yet - but the example templates html files are read already. Same goes for Partials & Layouts.

**Comment by NamelessCoder** [comment]
I actually considered putting these into the expected default locations of `Resources/Private/` so that's a good opportunity to also rename those folders. Makes sense to call the B one "Override" instead.

**Comment by NamelessCoder** [comment]
First step done - https://github.com/NamelessCoder/TYPO3.Fluid/commit/176930aeb5eb17fcf1bc6d323e5f379ddc5c7dae

**Comment by NamelessCoder** [comment]
And step two done - https://github.com/NamelessCoder/TYPO3.Fluid/commit/517b772587fd5cee80c2656e77e4eedca0cf7e29
