### ISSUE TITLE
Accessing to Foo->getTitle() not supportet?

### ISSUE THREAD

**Issue by pumatertion** [NamelessCoder/TYPO3.Fluid#6]
Hi Claus,
assigning a n object with public getter getTitle() isn't supported?
$this->view->assign('foo', new Foo());

I tried {foo.title} in the template but i returns always NULL.

**Comment by pumatertion** [comment]
Cant access these properties anymore.
Reopen it?

**Comment by pumatertion** [comment]
No, do not reopen it ^^
My fault :D
```
	public function getSource() {
		$this->source;
	}
```

**Comment by NamelessCoder** [comment]
Aaaaha :) explains a lot hehe.
