### ISSUE TITLE
Caching not in use for templates having sections

### ISSUE THREAD

**Issue by pumatertion** [NamelessCoder/TYPO3.Fluid#8]
For this html template file a cache is written:
```
<div>foo</div>
```

For this it is not written:
```
<f:render section="foo"/>
<f:section name="foo">
    <div>foo</div>
</f:section>
```

At the point you are using sections in a template, the cache is not in use.

**Comment by NamelessCoder** [comment]
Confirmed; working on a patch for this which also eliminates the CompilableInterface and likely introduces yet more performance improvements (depending on how the ViewHelperInvoker is implemented). More details later, of course :)

**Comment by pumatertion** [comment]
Thank you very much!
Also recognized, that an <f:if> leads to uncachable?

**Comment by NamelessCoder** [comment]
Any ViewHelper not implementing CompilableInterface would cause no caching to happen. That's the part I'm changing.

**Comment by NamelessCoder** [comment]
Should be fixed now - however, there is still some room for improvement when repeatedly calling ViewHelpers that use the default invocation method. In any case performance once compiled is at least as good as when not compiled even with the default invocation method.
