### ISSUE TITLE
Notice: Undefined index: cms in Core/ViewHelper/ViewHelperResolver.php on line 208

### ISSUE THREAD

**Issue by pumatertion** [NamelessCoder/TYPO3.Fluid#9]
Running into warnings and exceptions since https://github.com/NamelessCoder/TYPO3.Fluid/issues/8

Fatal error: Uncaught exception 'TYPO3\Fluid\Core\ViewHelper\Exception' with message ' in Core/ViewHelper/ViewHelperResolver.php on line 144

TYPO3\Fluid\Core\ViewHelper\Exception: The ViewHelper "<cms:node.translate>" could not be resolved. Based on your spelling, the system would load the class "\Node\TranslateViewHelper", however this class does not exist. in Core/ViewHelper/ViewHelperResolver.php on line 144

Namespace is already registered with:
```<f:fluid xmlns:cms="Bleicker\Cms\ViewHelpers"/>```

Exceptions only happen in production mode with enabled cache.
Without caching the templates the all work nice.

**Comment by NamelessCoder** [comment]
Use straight `<fluid>` tag for the xmlns - and make sure you use it as a container tag (not self-closed) if you want the autocompletion benefits in IDEs ;)

Examples will always use the right syntax, if you're ever in doubt!

**Comment by pumatertion** [comment]
Both does not work.
But maybe i am blind :)
Works only with uncached Fluid here :(

```<fluid xmlns:cms="Bleicker\\Cms\\ViewHelpers">
	<cms:node.translate propertyName="title">{page}</cms:node.translate>
</fluid>

<f:fluid xmlns:cms="Bleicker\\Cms\\ViewHelpers">
	<cms:node.translate propertyName="title">{page}</cms:node.translate>
</f:fluid>
```

**Comment by NamelessCoder** [comment]
Ah yes, I see your point. Problem was that the ViewHelperResolver was the only class responsible for returning the class names, but when a template had already been compiled, the namespaces detected during parse time were not stored as part of the compiled template.

Fixing that required a few additional changes and methods made public - please check if https://github.com/NamelessCoder/TYPO3.Fluid/commit/8ae88c688e39a00474da1a50eddbefcc1e6bc35e doesn't solve your issue, which I'm pretty sure it will ;)
